name = "Softly Optimized"
author = "NONPLAYT"
version = "1.19.4-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc8acc1972b4c9d84860ac719d749ef7e9f2055ab73fe886c60a4af18eae932e"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
