name = "Vanilla Reimagined"
author = "NONPLAYT"
version = "1.20.1-4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71a0a1ad3cbe42f7fd0defaeb265fe204d7987955ff1cd750a1c52455cefa6d1"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
