name = "Vanilla Reimagined"
author = "NONPLAYT"
version = "1.20.4-1.0.2-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1eae9d2380720336573e9c3cd4bc0f832016c864fc210572a3a061b0b0ca4ab5"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
