name = "Vanilla Reimagined"
author = "NONPLAYT"
version = "1.20.4-1.0.1-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4af2b363b9fad2cb25905652a5ead258c79b5ce3187dbc6b34e5f0498e062c14"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
