name = "Vanilla Reimagined"
author = "NONPLAYT"
version = "1.20.2-2.0.2-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a00cc3d7291e10892f3256296f6945943b0552cae82025ef527f3662c9dd8adf"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"

[options]
acceptable-game-versions = ["1.20.1"]
