name = "Vanilla Reimagined"
author = "NONPLAYT"
version = "1.20.1-3.0.4-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d39c79c30d1f5f787b7123f721565b7618c05b99af01e2e2904ebab653f48289"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
